config/routes.rb
Kvartplata::Application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions'}

  scope '(:locale)' do
    resources :metrics, :except => [:show]
    resources :tariffs
    resources :settings, :only => [:index] do
      collection do
        post :save
        post :save_apartment
      end
    end
    resources :reports, :only => [:index]
    get '/reports/:year/:month', :controller => :reports, :action => :show, :as => 'report_year_month'
    authenticated :user do
      root :to => 'welcome#index'
    end
    root :to => 'welcome#index'
    match ':controller/:action'
  end
end

app/models/metric.rb
require 'previous_month_value_validator'

class Metric < ActiveRecord::Base
  include ActiveModel::Validations

  attr_accessible :cold_counter_kitchen, :cold_counter_bathroom, :hot_counter_kitchen, :hot_counter_bathroom,
                  :energy_counter, :month

  validates_presence_of :cold_counter_kitchen, :cold_counter_bathroom,
                        :hot_counter_kitchen, :hot_counter_bathroom, :energy_counter

  validates :cold_counter_kitchen, :cold_counter_bathroom, :hot_counter_kitchen,
            :hot_counter_bathroom, :energy_counter, :numericality => { greater_than: 0.001}

  validates_that_greater_than_a_previous_value :cold_counter_kitchen, :cold_counter_bathroom,
                 :hot_counter_kitchen, :hot_counter_bathroom, :energy_counter

  has_many :reports, :foreign_key => 'current_metric_id'

  before_validation :round_month

  after_save :update_report

  PAYMENT_DAY = 20

  def previous_month
    @previous ||= Metric.where('month < ?',month).last
  end

  def next_month
    @next ||= Metric.where('month > ?',month).first
  end

  def -(value)
     Metric.new(
        :hot_counter_bathroom => hot_counter_bathroom - value.hot_counter_bathroom,
        :hot_counter_kitchen => hot_counter_kitchen - value.hot_counter_kitchen,
        :cold_counter_bathroom => cold_counter_bathroom - value.cold_counter_bathroom,
        :cold_counter_kitchen => cold_counter_kitchen - value.cold_counter_kitchen,
        :energy_counter => energy_counter - value.energy_counter
    )
  end

  def after_initialize
    @attributes['month'] = Chronic.parse(@attributes[:month]) unless @attributes[:month].blank?
  end

  def utilities
    hot_counter_bathroom + hot_counter_kitchen + cold_counter_bathroom + cold_counter_kitchen
  end

  def total_cold_water
    cold_counter_bathroom + cold_counter_kitchen
  end

  def total_hot_water
    hot_counter_bathroom + hot_counter_kitchen
  end

  def round_month
    self.month = month.round_to_month
  end

  def update_report
    if self.reports.empty?
      new_report = Report.from_metric(self)
      new_report.save if new_report
    else
      self.reports.each { |r| r.update_report! }
    end
  end

  def report
    Report.find_by_current_metric_id(self.to_param)
  end

  def ==(another_metric)

    (self.hot_counter_kitchen.in_delta_with hot_counter_kitchen) &&
    (self.hot_counter_bathroom.in_delta_with hot_counter_bathroom) &&
    (self.cold_counter_bathroom.in_delta_with cold_counter_bathroom) &&
    (self.hot_counter_bathroom.in_delta_with hot_counter_bathroom) &&
    (self.energy_counter.in_delta_with energy_counter) &&
    (self.month == another_metric.month)
  end

  class << self

    def time_to_pay?
      metric = Metric.where('month = ?', DateTime.now.round_to_month).last
      if metric.nil?
        return Metric.near_payment_day?
      end
      false
    end

    def near_payment_day?
      3.days.since.day >= PAYMENT_DAY
    end

    def months_with_data
      Metric.all.map { |metric| metric.month.strftime('%m/%Y') }
    end
  end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @metrics = Metric.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @metrics }
    end
  end


  def new
    @metric = Metric.new
    @metric.month = DateTime.now

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @metric }
    end
  end

  def edit
    @metric = Metric.find(params[:id])
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(params[:metric])

    respond_to do |format|
      if @metric.save
        format.html { @metric.report ? redirect_to(@metric.report.month_year_path) : redirect_to(new_metric_path) }
        format.json { render json: @metric, status: :created, location: @metric }
      else
        format.html { render action: 'new' }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /metrics/1
  # PUT /metrics/1.json
  def update
    @metric = Metric.find(params[:id])

    respond_to do |format|
      if @metric.update_attributes(params[:metric])
        format.html { @metric.report ? redirect_to(@metric.report.month_year_path) : redirect_to(new_metric_path,notice: 'Metric was successfully updated.') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric = Metric.find(params[:id])
    @metric.destroy

    respond_to do |format|
      format.html { redirect_to metrics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/metrics/_form.html.haml
#metrics_with_data{data: {metrics: Metric.months_with_data }}
= simple_form_for @metric, :html => { :class => 'form-horizontal'},  :validate => true  do |f|

  = f.input :month, label: 'месяц',  :as => :date_picker, :input_html => { :id => 'monthsDatepicker'}, :format => :short_month_year

  %h4 кухня
  = f.input :cold_counter_kitchen, label: 'холодная вода'
  = f.input :hot_counter_kitchen,  label: 'горячая вода'

  %h4 ванная
  = f.input :cold_counter_bathroom, label: 'холодная вода'
  = f.input :hot_counter_bathroom,  label: 'горячая вода'

  %h4 свет
  = f.input :energy_counter, label:'электроэнергия'
  = f.submit 'сохранить', :class => 'btn btn-primary span2'

app/views/metrics/edit.html.haml
%h1 Editing metric

= render 'form'

= link_to 'Show', @metric
|
= link_to 'Back', metrics_path

app/views/metrics/index.html.haml
%h1 Listing metrics

%table
  %tr
    %th
    %th
    %th
- @metrics.each do |metric|
  %tr
    %td
      = link_to 'Show', metric
    %td
      = link_to 'Edit', edit_metric_path(metric)
    %td
      = link_to 'Destroy', metric, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Metric', new_metric_path

app/views/metrics/new.html.haml
.new_metric
  %h2 занести показания

  = render 'form'

app/views/metrics/show.html.haml
%p#notice
  = notice

= link_to 'Edit', edit_metric_path(@metric)
|
= link_to 'Back', metrics_path