config/routes.rb
Kvartplata::Application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions'}

  scope '(:locale)' do
    resources :metrics, :except => [:show]
    resources :tariffs
    resources :settings, :only => [:index] do
      collection do
        post :save
        post :save_apartment
      end
    end
    resources :reports, :only => [:index]
    get '/reports/:year/:month', :controller => :reports, :action => :show, :as => 'report_year_month'
    authenticated :user do
      root :to => 'welcome#index'
    end
    root :to => 'welcome#index'
    match ':controller/:action'
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  before_filter :authenticate_user!
  def index
    @user = current_user
    respond_to do |format|
      format.html
    end
  end

  def save
    @settings =  current_user.notification_settings

    respond_to do |format|
      if @settings.update_attributes(params[:notification_settings])
        format.html { redirect_to settings_path, notice: 'настройки успешно сохранены' }
      end
    end
  end

  def save_apartment
    @apartment_info =  current_user.apartment_info

    respond_to do |format|
      if @apartment_info.update_attributes(params[:apartment_info])
        format.html { redirect_to settings_path, notice: 'настройки успешно сохранены' }
      end
    end
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_information_settings_form.html.haml
.settings-form
  = simple_form_for apartment_info, :url => save_apartment_settings_path, :method => :post, :html => { :class => 'form-horizontal'},
    :validate => true  do |f|
    = f.input :owner, :label => 'владелец'
    = f.input :address, :label => 'адрес дома'
    = f.input :number, :label => 'номер квартиры'
    = f.submit 'сохранить', :class => 'btn btn-primary span2'

app/views/settings/_notification_settings_form.html.haml
.settings-form
  = simple_form_for notification_settings, :url => save_settings_path, :method => :post, :html => { :class => 'form-horizontal'},
    :validate => true  do |f|
    = f.input :enabled, :label => 'включить уведомления', :wrapper => :inline_checkbox
    .inner
      = f.input :notify_by_email, :label => 'почта', :wrapper => :inline_checkbox
      = f.input :notify_by_phone, :label => 'SMS', :wrapper => :inline_checkbox
      = f.input :day, :label => 'день уведомления', :as => :select, :collection => (1..31).to_a
      .row.notification-time
        .hours
          = f.input :hour, :label => 'время уведомления', :as => :select, :collection => (0..23).to_a
        .minutes
          = f.input :minute, :label => false, :as => :select, :collection => (0..59).map {|min| '%02d' % min}.to_a,
            :selected => '%02d' % notification_settings.minute
    = f.submit 'сохранить', :class => 'btn btn-primary span2'

app/views/settings/index.html.haml
%h2 настройки
.tabbable.tabs-left
  %ul.nav.nav-tabs
    %li.active
      %a{:href => '#general',:data => {:toggle => :tab}} инфо
    %li
      %a{:href => '#notifications',:data => {:toggle => :tab}} уведомления
    %li
      %a{:href => '#services',:data => {:toggle => :tab}} интеграция

  .tab-content
    #general.tab-pane.active
      = render :partial => 'settings/information_settings_form', :locals => {:apartment_info => @user.apartment_info}
    #notifications.tab-pane
      = render :partial => 'settings/notification_settings_form', :locals => { :notification_settings => @user.notification_settings}
    #services.tab-pane
      %p в следующих версиях