config/routes.rb
Kvartplata::Application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions'}

  scope '(:locale)' do
    resources :metrics, :except => [:show]
    resources :tariffs
    resources :settings, :only => [:index] do
      collection do
        post :save
        post :save_apartment
      end
    end
    resources :reports, :only => [:index]
    get '/reports/:year/:month', :controller => :reports, :action => :show, :as => 'report_year_month'
    authenticated :user do
      root :to => 'welcome#index'
    end
    root :to => 'welcome#index'
    match ':controller/:action'
  end
end

app/models/tariff.rb
require 'chronic'
class Tariff < ActiveRecord::Base
  attr_accessible :start_date, :end_date, :cold_water, :hot_water,
                  :energy, :utilities, :comments
  has_many :reports

  validates_presence_of :start_date, :cold_water, :hot_water, :energy, :utilities

  validates :cold_water, :hot_water, :energy, :utilities, numericality: {greater_than: 0.01}

  def previous
    Tariff.where('end_date < ?',start_date).last(:order => 'end_date') if Tariff.all.size > 1
  end

  def after_initialize
    @attributes['start_date'] = Chronic.parse(@attributes[:start_date]) unless @attributes[:start_date].blank?
    @attributes['end_date'] = Chronic.parse(@attributes[:end_date]) unless @attributes[:end_date].blank?
  end

  class << self

    def is_there_more_than_two?
      Tariff.all.size > 2
    end

    def that_was(month)
      Tariff.where('start_date <= :month AND end_date >= :month', month: month).last
    end
  end
end

app/controllers/tariffs_controller.rb
class TariffsController < ApplicationController
  # GET /tariffs
  # GET /tariffs.json
  def index
    @tariffs = Tariff.all(:order => 'start_date DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tariffs }
    end
  end

  # GET /tariffs/1
  # GET /tariffs/1.json
  def show
    @tariff = Tariff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tariff }
    end
  end

  # GET /tariffs/new
  # GET /tariffs/new.json
  def new
    @tariff = Tariff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tariff }
    end
  end

  # GET /tariffs/1/edit
  def edit
    @tariff = Tariff.find(params[:id])
  end

  # POST /tariffs
  # POST /tariffs.json
  def create
    @tariff = Tariff.new(params[:tariff])

    respond_to do |format|
      if @tariff.save
        format.html { redirect_to tariffs_url, notice: 'Tariff was successfully created.' }
        format.json { render json: @tariff, status: :created, location: @tariff }
      else
        format.html { render action: "new" }
        format.json { render json: @tariff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tariffs/1
  # PUT /tariffs/1.json
  def update
    @tariff = Tariff.find(params[:id])

    respond_to do |format|
      if @tariff.update_attributes(params[:tariff])
        format.html { redirect_to tariffs_url, notice: 'Tariff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tariff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tariffs/1
  # DELETE /tariffs/1.json
  def destroy
    @tariff = Tariff.find(params[:id])
    @tariff.destroy

    respond_to do |format|
      format.html { redirect_to tariffs_url }
      format.json { head :no_content }
      format.js { render js: %(window.location.href='#{tariffs_url}') }
    end
  end
end

app/helpers/tariffs_helper.rb
module TariffsHelper
  def current_tariff
    @current_tariff ||= Tariff.where('start_date <= ?',Date.today).order('start_date ASC').last
  end

  def previous_tariff
    @previous_tariff ||= Tariff.where('start_date < ?',current_tariff.start_date).order('start_date ASC').last
  end
end

app/views/tariffs/_form.html.haml
= simple_form_for @tariff, :html => { :class => 'form-horizontal'},  :validate => true  do |f|

  = f.input :hot_water, label: 'горячая вода', placeholder: current_tariff.hot_water.to_s
  = f.input :cold_water,  label: 'холодная вода', placeholder: current_tariff.cold_water.to_s
  = f.input :utilities,  label: 'водоотведение', placeholder: current_tariff.utilities.to_s
  = f.input :energy, label:'электроэнергия', placeholder: current_tariff.energy.to_s

  = f.input :start_date, label: 'дата начала',  :as => :date_picker
  = f.input :end_date, label: 'дата окончания', :as => :date_picker

  = f.submit 'сохранить', :class => 'btn btn-primary span2'

app/views/tariffs/_side_widget.haml
.tariff_widget
  %h3 текущие тарифы
  .row
    .span2.names
      %p горячая вода
      %p холодная вода
      %p водоотведение
      %p электроэнергия

    .values
      %p
        = tariff.hot_water
        р / м3
      %p
        = tariff.cold_water
        р / м3
      %p
        = tariff.utilities
        р / м3
      %p
        = tariff.energy
        р / квт-ч

app/views/tariffs/_tariff_brief.html.haml
.tariff
  .header
    -if tariff == current_tariff
      %h4 текущий тариф ( c #{l(tariff.start_date.to_date, :format => :long)} )
    -else
      - start_date = tariff.start_date ? l(tariff.start_date.to_date, format: :long) : ''
      - end_date = tariff.end_date ? l(tariff.end_date.to_date, format: :long) : ''
      %h4 c #{start_date} по #{end_date}
    .icons
      = link_to edit_tariff_path(tariff) do
        %i.icon-pencil{:title => 'редактировать тариф'}
      %i.icon-remove{:title => 'удалить тариф', :data => {:url => "#{tariff_path(tariff)}" }}
  %div{:class => 'tariff-body'}
    .names.span3
      %p горячая вода
      %p холодная вода
      %p водоотведение
      %p электроэнергия
    .values
      %p #{tariff.hot_water} р
      %p #{tariff.cold_water} р
      %p #{tariff.utilities} р
      %p #{tariff.energy} р

app/views/tariffs/edit.html.haml
.new-tariff
  %h2 изменить тариф
  = render 'form'

app/views/tariffs/index.html.haml
.toTop
  %i.icon-arrow-up

= link_to new_tariff_path, {:class => 'add-tariff'} do
  %i.icon-plus
  %span добавить тариф

=render :partial => 'tariffs/tariff_brief', :locals => {:tariff => current_tariff}
- if previous_tariff
  =render :partial => 'tariffs/tariff_brief', :locals => {:tariff => previous_tariff}

- if Tariff.is_there_more_than_two?
  %span{:class => 'show-more-tariffs', :data => {:status => 'collapsed'}} #{'▾ показать все'.html_safe}
  .other-tariffs
    - @tariffs.each do |tariff|
      = render :partial => 'tariffs/tariff_brief', :locals => {:tariff => tariff} unless (tariff == current_tariff or tariff == previous_tariff)

app/views/tariffs/new.html.haml
.new-tariff
  %h2 новый тариф
  = render 'form'

app/views/tariffs/show.html.haml
%p#notice= notice

= link_to 'Edit', edit_tariff_path(@tariff)
= link_to 'Back', tariffs_path