config/routes.rb
Kvartplata::Application.routes.draw do

  devise_for :users, :controllers => {sessions: 'sessions'}

  scope '(:locale)' do
    resources :metrics, :except => [:show]
    resources :tariffs
    resources :settings, :only => [:index] do
      collection do
        post :save
        post :save_apartment
      end
    end
    resources :reports, :only => [:index]
    get '/reports/:year/:month', :controller => :reports, :action => :show, :as => 'report_year_month'
    authenticated :user do
      root :to => 'welcome#index'
    end
    root :to => 'welcome#index'
    match ':controller/:action'
  end
end

app/views/layouts/application.html.haml
!!!
%head
  %title Kvartplata
  = stylesheet_link_tag    'application', :media => 'all'
  = stylesheet_link_tag 'print/print', :media => 'print'
  = stylesheet_link_tag 'bootstrap/bootstrap-responsive.min', :media =>  'screen'
  = javascript_include_tag 'application'
  = csrf_meta_tags
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600,700&subset=latin,cyrillic-ext'

%body
.container
  .navbar.navbar-fixed-top
    .navbar-inner
      .fixed-width-nav.user
        %ul.nav
          %li
            %h3
              %a.brand{:href => '/'} Kvartplata
          %li
            = link_to 'занести показания', new_metric_path
          %li
            = link_to 'отчеты', reports_path
          %li
            = link_to 'тарифы', tariffs_path
          %li
            = link_to 'настройки', settings_path
        .user-nav
          - if user_signed_in?
            %italic
              = current_user.email
            = link_to 'выйти', destroy_user_session_path, method: :delete
          - else
            %li.dropdown{:data => {:dropdown => 'dropdown'}}
              = link_to 'войти', :class => 'dropdown-toggle'
              .dropdown-menu{:role => 'menu'}
                =render :partial => 'devise/sessions/form'

  .row
    %section.content.span7.offset1
      .report
        = yield
    %aside.aside.span4
      %section.side_widget
        = render :partial => 'reports/side_widget'
      %section.side_widget
        = render :partial => 'tariffs/side_widget', :locals => {tariff: current_tariff}

app/views/layouts/devise.html.haml
!!!
%html
%head
  %title Kvartplata
  = stylesheet_link_tag    'application', :media => 'all'
  = stylesheet_link_tag 'print/print', :media => 'print'
  = stylesheet_link_tag 'bootstrap/bootstrap-responsive.min', :media =>  'screen'
  = javascript_include_tag 'application'
  = csrf_meta_tags
  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600,700&subset=latin,cyrillic-ext'

%body
.container
  .navbar.navbar-fixed-top
    .navbar-inner
      .fixed-width-nav.anon
        %ul.nav
          %li
            %h3
              %a.brand{:href => '/'} Kvartplata

        .user-nav
          - if user_signed_in?
            %italic
              = current_user.email
            = link_to 'выйти', destroy_user_session_path, method: :delete
          - else
            .dropdown
              = link_to 'войти','#', :class => 'dropdown-toggle btn', :data => {:toggle => 'dropdown'}
              .dropdown-menu{:role => 'menu',:aria=>{:labelledby=>'dLabel'}}
                =render :partial => 'devise/sessions/form'

  .row
    = yield